### ISSUE TITLE
Missing a comma

### ISSUE THREAD

**Issue by ynunokawa** [muxlab/map-effects-100#19]
assets/style.css and Map Effect No.11-14
- between `"Meiryo"` and `Helvetica`

``` css
html, body, #map {
  height: 600px;
  font-family: "Avenir LT W01 35 Light", "Century Gothic", "Meiryo" Helvetica, Arial, sans-serif;
}
```
