### ISSUE TITLE
IOS Safari transition not working

### ISSUE THREAD

**Issue by ynunokawa** [muxlab/map-effects-100#3]
The below css is not working on iOS Safari.

``` css
-webkit-transition: r 4s;
```

However D3.transition() is working.
We try to replace every example to use transition into D3 solution.

``` javascript
d3.select('circle#' + properties['code'])
                        .transition()
                        .delay(0)
                        .duration(4000)
                        .attr('r', properties['mag']*2.5)
```
### Targeted examples
- [x] https://github.com/muxlab/map-effects-100/blob/gh-pages/Leaflet/08_time-animation.html
- [x] https://github.com/muxlab/map-effects-100/blob/gh-pages/Leaflet/09_nearest-with-turf.html

**Comment by ynunokawa** [comment]
FYI, It is working if using fill or stroke, something properties.

``` css
svg.leaflet-zoom-animated > g > path {
          transition-property: fill, fill-opacity, stroke, stroke-opacity, stroke-width;
          transition-duration: 0.4s;
        }
```
